# Generated by Django 4.2 on 2023-05-17 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_author_id_alter_author_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_moderator', to='mainapp.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
