# Generated by Django 4.2 on 2023-05-17 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_moderator_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='cat',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_moderator', to='mainapp.category', verbose_name='Категория'),
        ),
    ]
