# Generated by Django 4.2 on 2023-05-05 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='moderator',
            options={'verbose_name': 'Модератор', 'verbose_name_plural': 'Модераторы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Все пользователи', 'verbose_name_plural': 'Все пользователи'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_article', to='mainapp.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='like',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_from', to='mainapp.author'),
        ),
        migrations.AlterField(
            model_name='like',
            name='to_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_article', to='mainapp.article'),
        ),
        migrations.AlterField(
            model_name='like',
            name='to_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_comment', to='mainapp.comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_to', to='mainapp.author'),
        ),
    ]
