# Generated by Django 4.2 on 2023-04-05 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_moderator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Дизайн', 'Disign'), ('Web разработка', 'Web'), ('Мобильная разработка', 'Mobile'), ('Маркетинг', 'Marleting')], default='Web разработка', max_length=20)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('short_description', models.TextField(max_length=300, verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='Причина обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('is_deleted', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_author', to='articles.user', verbose_name='Автор статьи')),
            ],
        ),
    ]
